# Generated by Django 5.2.11 on 2026-02-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_product_metrics_affected"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_critical",
            new_name="active_critical",
        ),
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_high",
            new_name="active_high",
        ),
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_low",
            new_name="active_low",
        ),
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_medium",
            new_name="active_medium",
        ),
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_none",
            new_name="active_none",
        ),
        migrations.RenameField(
            model_name="product_metrics",
            old_name="open_unknown",
            new_name="active_unknown",
        ),
    ]
