# Generated by Django 6.0.3 on 2026-03-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_product_last_license_change"),
        ("metrics", "0004_rename_open_critical_product_metrics_active_critical_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_License_Metrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("allowed", models.IntegerField(default=0)),
                ("forbidden", models.IntegerField(default=0)),
                ("ignored", models.IntegerField(default=0)),
                ("review_required", models.IntegerField(default=0)),
                ("unknown", models.IntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product")),
            ],
            options={
                "unique_together": {("product", "date")},
            },
        ),
    ]
