export type ThemeName = "light" | "dark";

declare global {
    interface Window {
        restServer: any;
    }
}

export const VEX_JUSTIFICATION_TYPE_CSAF_OPENVEX = "CSAF/OpenVEX";
export const VEX_JUSTIFICATION_TYPE_CYCLONEDX = "CycloneDX";

export const VEX_JUSTIFICATION_TYPE_CHOICES = [
    { id: VEX_JUSTIFICATION_TYPE_CSAF_OPENVEX, name: VEX_JUSTIFICATION_TYPE_CSAF_OPENVEX },
    { id: VEX_JUSTIFICATION_TYPE_CYCLONEDX, name: VEX_JUSTIFICATION_TYPE_CYCLONEDX },
];

export const METRICS_TIMESPAN_7_DAYS = "Week";
export const METRICS_TIMESPAN_30_DAYS = "Month";
export const METRICS_TIMESPAN_90_DAYS = "Quarter";
export const METRICS_TIMESPAN_365_DAYS = "Year";

export const METRICS_TIMESPAN_CHOICES = [
    { id: METRICS_TIMESPAN_7_DAYS, name: METRICS_TIMESPAN_7_DAYS },
    { id: METRICS_TIMESPAN_30_DAYS, name: METRICS_TIMESPAN_30_DAYS },
    { id: METRICS_TIMESPAN_90_DAYS, name: METRICS_TIMESPAN_90_DAYS },
    { id: METRICS_TIMESPAN_365_DAYS, name: METRICS_TIMESPAN_365_DAYS },
];
