{{- if or .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ing" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "secobserve.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-svc" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
                port:
                  name: backend-http
          - path: /django-static/
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-svc" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
                port:
                  name: backend-http
          {{- with .Values.ingress.paths }}
          {{- tpl (toYaml .) $ | nindent 10 }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-svc" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
                port:
                  name: frontend-http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
