apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "secobserve.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: frontend-http
      port: {{ .Values.frontend.service.port }}
      targetPort: frontend-http
      protocol: TCP
    - name: backend-http
      port: {{ .Values.backend.service.port }}
      targetPort: backend-http
      protocol: TCP
  selector:
    {{- include "secobserve.selectorLabels" . | nindent 4 }}
