apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-sts" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "secobserve.labels" . | nindent 4 }}
spec:
  serviceName: {{ printf "%s-svc" (include "secobserve.fullname" .) | trunc 63 | trimSuffix "-" }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secobserve.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- include "secobserve.selectorLabels" . | nindent 8 }}
    spec:
      {{- if or .Values.dbchecker.enabled .Values.extraInitContainers }}
      initContainers:
        {{- if and .Values.dbchecker.enabled }}
        - name: dbchecker
          image: "{{ .Values.dbchecker.image.repository }}{{- if (.Values.dbchecker.image.digest) -}}@{{ .Values.dbchecker.image.digest }}{{- else -}}:{{ .Values.dbchecker.image.tag }} {{- end }}"
          imagePullPolicy: {{ .Values.dbchecker.image.pullPolicy }}
          {{- if .Values.dbchecker.securityContext.enabled }}
          securityContext:
            {{- omit .Values.dbchecker.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command:
            - sh
            - -c
            - |
              echo 'Waiting for Database to become ready...'

              until printf "." && nc -z -w 2 {{ default (include "secobserve.databaseHost" .) .Values.dbchecker.hostname }} {{ default .Values.database.port .Values.dbchecker.port }}; do
                  sleep 2;
              done;

              echo 'Database OK ✓'
          resources:
            {{- toYaml .Values.dbchecker.resources | nindent 12 }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        {{ omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: frontend-http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 300
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.securityContext.enabled }}
          securityContext:
            {{- omit .Values.frontend.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}

        - name: backend
          image: "{{ .Values.backend.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            {{- include "secobserve.backendEnv" . | nindent 12 }}
          ports:
            - name: backend-http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/status/health/
              port: 5000
            initialDelaySeconds: 300
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /api/status/health/
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- if or .Values.huey.persistence.enabled .Values.backend.volumeMounts }}
          volumeMounts:
            {{- if .Values.huey.persistence.enabled }}
            - name: huey
              mountPath: /var/lib/huey
            {{- end }}
            {{- with .Values.backend.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.backend.securityContext.enabled }}
          securityContext:
            {{- omit .Values.backend.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}

      {{- if or .Values.huey.persistence.enabled .Values.frontend.volumes .Values.backend.volumes }}
      volumes:
        {{- if .Values.huey.persistence.enabled }}
        - name: huey
          persistentVolumeClaim:
            claimName: {{ include "secobserve.huey.claimName" . }}
        {{- end }}
        {{- with .Values.frontend.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.backend.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
