# Generated by Django 4.2.11 on 2024-03-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_observation_assessment_vex_justification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="duplicate_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicates",
                to="core.observation",
            ),
        ),
    ]
