# Generated by Django 4.2.11 on 2024-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_observation_duplicate_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_component_location",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
