# Generated by Django 4.2.11 on 2024-03-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_branch_cpe23_branch_purl"),
        ("core", "0034_observation_origin_component_location"),
    ]

    operations = []
