# Generated by Django 4.2.11 on 2024-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_merge_20240315_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
