# Generated by Django 4.2.11 on 2024-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_observation_origin_component_dependencies"),
        ("core", "0037_alter_observation_assessment_status_and_more"),
    ]

    operations = []
