# Generated by Django 4.2.11 on 2024-03-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_observation_log_approval_date_and_more"),
        ("core", "0038_merge_20240321_1153"),
    ]

    operations = []
