# Generated by Django 4.2.11 on 2024-04-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_product_authorization_group_member"),
        ("core", "0039_merge_20240329_1351"),
    ]

    operations = []
