# Generated by Django 4.2.11 on 2024-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_20240402_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="stackable_score",
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
