# Generated by Django 4.2.11 on 2024-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_observation_stackable_score"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["stackable_score"], name="core_observ_stackab_f65ce5_idx"
            ),
        ),
    ]
