# Generated by Django 4.2.11 on 2024-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_observation_core_observ_stackab_f65ce5_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="patched_in_versions",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
