# Generated by Django 4.2.11 on 2024-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_observation_patched_in_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="patch_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["patch_available"], name="core_observ_patch_a_6e4989_idx"
            ),
        ),
    ]
