# Generated by Django 4.2.11 on 2024-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_observation_patch_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation_log",
            name="comment",
            field=models.TextField(),
        ),
    ]
