# Generated by Django 4.2.11 on 2024-04-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_observation_log_comment"),
        ("core", "0045_alter_observation_log_comment"),
    ]

    operations = []
