# Generated by Django 4.2.11 on 2024-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_observation_exploits"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="purl_type",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
