# Generated by Django 5.0.4 on 2024-05-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_parser_class_name_parser_module_name"),
        ("core", "0051_observation_purl_type"),
    ]

    operations = []
