# Generated by Django 5.0.6 on 2024-06-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_observation_vex_statement_observation_vex_status_and_more"),
        ("core", "0052_merge_20240506_1917"),
    ]

    operations = []
