# Generated by Django 5.0.6 on 2024-06-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_merge_20240623_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="vex_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Not security", "Not security"),
                    ("Risk accepted", "Risk accepted"),
                    ("Affected", "Affected"),
                ],
                max_length=16,
            ),
        ),
    ]
