# Generated by Django 5.0.6 on 2024-07-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_observation_risk_acceptance_expiry_date_and_more"),
        ("core", "0054_alter_observation_vex_status"),
    ]

    operations = []
