# Generated by Django 5.0.6 on 2024-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_merge_20240710_1516"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observation",
            old_name="vex_remediations",
            new_name="current_vex_remediations",
        ),
        migrations.AddField(
            model_name="observation",
            name="assessment_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="vex_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
