# Generated by Django 5.0.7 on 2024-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0056_rename_vex_remediations_observation_current_vex_remediations_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="origin_component_dependencies",
            field=models.TextField(blank=True, max_length=32768),
        ),
    ]
