# Generated by Django 5.0.8 on 2024-08-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_merge_20240819_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='purl_type',
        ),
    ]
