# Generated by Django 5.0.8 on 2024-08-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_observation_origin_component_dependencies"),
        ("core", "0058_remove_observation_purl_type"),
    ]

    operations = []
