# Generated by Django 5.0.8 on 2024-09-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_observation_origin_kubernetes_cluster_and_more"),
        ("core", "0059_merge_20240820_1651"),
    ]

    operations = []
