# Generated by Django 5.1.1 on 2024-10-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_convert_origin_component_dependencies"),
        ("core", "0060_merge_20240903_1725"),
    ]

    operations = []
