# Generated by Django 5.1.2 on 2024-10-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_product_license_policy"),
        ("core", "0061_merge_20241004_1107"),
    ]

    operations = []
