# Generated by Django 5.1.2 on 2024-10-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_convert_unknown_data'),
        ('core', '0062_merge_20241022_1454'),
    ]

    operations = [
    ]
