# Generated by Django 5.1.3 on 2024-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_merge_20241028_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation_log",
            name="approval_remark",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="observation_log",
            name="comment",
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
