# Generated by Django 5.1.3 on 2024-11-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_product_authorization_group_members"),
        ("core", "0064_alter_observation_log_approval_remark_and_more"),
    ]

    operations = []
