# Generated by Django 5.1.4 on 2024-12-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_correct_risk_acceptance_expiry_date"),
        ("core", "0065_merge_20241125_2321"),
    ]

    operations = []
