# Generated by Django 5.1.4 on 2024-12-19 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_merge_20241216_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="upgrade_impact_score",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
