# Generated by Django 5.1.4 on 2024-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_observation_upgrade_impact_score"),
        (
            "import_observations",
            "0010_vulnerability_check_last_import_licenses_deleted_and_more",
        ),
        ("rules", "0017_alter_rule_approval_remark"),
        ("vex", "0007_alter_csaf_tracking_current_release_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["upgrade_impact_score"], name="core_observ_upgrade_f3aeed_idx"),
        ),
    ]
