# Generated by Django 5.1.5 on 2025-03-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_observation_cve_found_in_and_more"),
        ("core", "0069_merge_20250120_2305"),
    ]

    operations = []
