# Generated by Django 5.2.8 on 2025-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_components_view_open_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="osv_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
