# Generated by Django 5.1.7 on 2025-03-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_branch_osv_linux_distribution_and_more"),
        ("core", "0070_merge_20250328_1143"),
    ]

    operations = []
