# Generated by Django 5.2.9 on 2025-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_product_osv_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_default_branch",
            field=models.BooleanField(default=False),
        ),
    ]
