# Generated by Django 5.1.7 on 2025-04-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_merge_20250331_1956"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="observation",
            name="core_observ_in_vuln_bb4e6d_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="core_observ_exploit_bc386d_idx",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="exploit_available",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="in_vulncheck_kev",
        ),
    ]
