# Generated by Django 5.2.1 on 2025-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_observation_origin_source_file_link"),
        ("core", "0073_delete_exploit_and_more"),
    ]

    operations = []
