# Generated by Django 5.2.10 on 2026-01-11 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_initialize_default_branch"),
        ("import_observations", "0016_api_configuration_migrate_names"),
        ("rules", "0016_alter_rule_new_vex_justification"),
        ("vex", "0010_cyclonedx_cyclonedx_branch_cyclonedx_vulnerability"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="fix_available",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="update_impact_score",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["update_impact_score"], name="core_observ_update__10b05f_idx"),
        ),
    ]
