# Generated by Django 5.2.4 on 2025-07-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_product_description_markdown"),
        ("core", "0074_merge_20250615_1552"),
    ]

    operations = []
