# Generated by Django 5.2.7 on 2025-10-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_components_view_open_observations"),
        ("core", "0075_merge_20250715_1104"),
    ]

    operations = []
