# Generated by Django 5.2.11 on 2026-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_observation_initialize_fix_and_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="notification_ms_teams_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="product",
            name="notification_slack_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
