# Generated by Django 5.2.9 on 2026-01-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_initialize_default_branch"),
        ("core", "0076_merge_20251010_1715"),
    ]

    operations = []
