# Generated by Django 5.2.11 on 2026-02-11 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_drop_component_view"),
        ("import_observations", "0016_api_configuration_migrate_names"),
        ("rules", "0018_rule_rego_module_rule_type"),
        ("vex", "0010_cyclonedx_cyclonedx_branch_cyclonedx_vulnerability"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="assessment_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="current_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="general_rule_rego",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_rules_rego",
                to="rules.rule",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="product_rule_rego",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_rules_rego",
                to="rules.rule",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_rego_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_rego_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_rego_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Not security", "Not security"),
                    ("Risk accepted", "Risk accepted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_rego_vex_justification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("component_not_present", "component_not_present"),
                    ("vulnerable_code_not_present", "vulnerable_code_not_present"),
                    (
                        "vulnerable_code_cannot_be_controlled_by_adversary",
                        "vulnerable_code_cannot_be_controlled_by_adversary",
                    ),
                    ("vulnerable_code_not_in_execute_path", "vulnerable_code_not_in_execute_path"),
                    ("inline_mitigations_already_exist", "inline_mitigations_already_exist"),
                    ("code_not_present", "code_not_present"),
                    ("code_not_reachable", "code_not_reachable"),
                    ("requires_configuration", "requires_configuration"),
                    ("requires_dependency", "requires_dependency"),
                    ("requires_environment", "requires_environment"),
                    ("protected_by_compiler", "protected_by_compiler"),
                    ("protected_at_runtime", "protected_at_runtime"),
                    ("protected_at_perimeter", "protected_at_perimeter"),
                    ("protected_by_mitigating_control", "protected_by_mitigating_control"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["current_priority"], name="core_observ_current_ba21e4_idx"),
        ),
    ]
