# Generated by Django 5.2.10 on 2026-01-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_observation_initialize_fix_and_upgrade"),
        ("core", "0077_merge_20260102_1149"),
    ]

    operations = []
