# Generated by Django 5.2.10 on 2026-01-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_merge_20260115_1242"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="observation",
            name="core_observ_patch_a_6e4989_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="core_observ_upgrade_f3aeed_idx",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="patch_available",
        ),
    ]
