# Generated by Django 5.2.11 on 2026-03-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_alter_observation_assessment_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="observation",
            name="core_observ_origin__43587c_idx",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="origin_service_name",
        ),
    ]
