# Generated by Django 5.2.11 on 2026-02-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_alter_product_notification_ms_teams_webhook_and_more"),
        ("core", "0079_remove_observation_core_observ_patch_a_6e4989_idx_and_more"),
    ]

    operations = []
