# Generated by Django 5.2.12 on 2026-03-08 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_remove_observation_core_observ_origin__43587c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="observation_notification_min_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="observation_notification_min_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="observation_notification_statuses",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
