# Generated by Django 5.2.11 on 2026-02-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_alter_observation_assessment_status_and_more"),
        ("core", "0080_merge_20260213_1257"),
    ]

    operations = []
