# Generated by Django 6.0.3 on 2026-03-29 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_product_observation_notification_min_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_license_change",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
