# Generated by Django 5.2.9 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_merge_20260219_1320"),
        ("core", "0081_product_observation_notification_min_priority_and_more"),
    ]

    operations = []
