# Generated by Django 5.2.9 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_product_last_license_change"),
        ("core", "0083_alter_observation_assessment_status_and_more"),
    ]

    operations = []
