# Generated by Django 6.0.3 on 2026-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_product_last_license_change"),
        ("import_observations", "0016_api_configuration_migrate_names"),
        ("rules", "0019_alter_rule_new_status"),
        ("vex", "0010_cyclonedx_cyclonedx_branch_cyclonedx_vulnerability"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["origin_component_purl"], name="core_observ_origin__2b1af9_idx"),
        ),
    ]
