# Generated by Django 6.0.3 on 2026-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_merge_20260330"),
        ("core", "0083_observation_core_observ_origin__2b1af9_idx"),
    ]

    operations = []
