# Generated by Django 6.0.4 on 2026-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_merge_20260407_1152"),
        ("core", "0084_observation_origin_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="description",
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
