# Generated by Django 6.0.4 on 2026-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_merge_20260407_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
