# Generated by Django 6.0.5 on 2026-05-16 14:28
# Stackable: upstream 0086 also added assessment/current/rule/vex_vex_remediations and
# observation_log.vex_remediations, but those already exist in the stackable schema via
# earlier migrations (0036/0056). Only rule_rego_vex_remediations is genuinely new.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_alter_observation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="rule_rego_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
