# Generated by Django 6.0.6 on 2026-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_resave_encrypt_issue_tracker_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observation_log",
            old_name="approval_remark",
            new_name="rejection_remark",
        ),
        migrations.AlterField(
            model_name="observation_log",
            name="assessment_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Approved with edits", "Approved with edits"),
                    ("Needs approval", "Needs approval"),
                    ("Rejected", "Rejected"),
                    ("Auto approved", "Auto approved"),
                    ("Removed", "Removed"),
                ],
                default="Auto approved",
                max_length=20,
            ),
        ),
    ]
