# Generated by Django 6.0.6 on 2026-06-16 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0018_user_setting_rows_per_page"),
        ("core", "0089_rename_approval_remark_observation_log_rejection_remark_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="assessment_approver_authorization_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="assessment_approver_group_for_products",
                to="access_control.authorization_group",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="assessment_approvers",
            field=models.ManyToManyField(
                blank=True, related_name="assessment_approver_for_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
