# Generated by Django 6.0.6 on 2026-07-04 12:24

from django.db import migrations, models
from django.db.models.deletion import SET_NULL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_product_assessment_approver_authorization_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="propagate_branches",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="propagated_from",
            field=models.ForeignKey(blank=True, null=True, on_delete=SET_NULL, to="core.observation_log"),
        ),
    ]
