# Generated by Django 6.0.6 on 2026-07-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_product_propagate_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="propagate_branches_new_assessment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="propagate_branches_new_observation",
            field=models.BooleanField(default=True),
        ),
    ]
