# Generated by Django 6.0.7 on 2026-07-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_observation_log_general_rule_rego_and_more"),
        ("rules", "0021_rename_approval_remark_rule_rejection_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="general_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="general_rules",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="general_rule_rego",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="general_rules_rego",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="origin_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.service",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product"),
        ),
        migrations.AlterField(
            model_name="observation",
            name="product_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="product_rules",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="product_rule_rego",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="product_rules_rego",
                to="rules.rule",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.product",
            ),
        ),
    ]
