# Generated by Django 6.0.7 on 2026-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_alter_observation_general_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation_log",
            name="priority_changed",
            field=models.BooleanField(default=False),
        ),
    ]
