# Generated by Django 6.0.7 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_initialize_observation_log_priority_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation_log",
            name="rejection_remark",
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
