# Generated by Django 6.0.8 on 2026-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_initialize_observation_log_priority_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="automatic_vulnerablecode_scanning_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="vulnerablecode_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
