# Generated by Django 6.0.4 on 2026-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0020_license_component_component_cyclonedx_bom_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Application", "Application"),
                    ("Framework", "Framework"),
                    ("Library", "Library"),
                    ("Container", "Container"),
                    ("Platform", "Platform"),
                    ("Operating system", "Operating system"),
                    ("Device", "Device"),
                    ("Device driver", "Device driver"),
                    ("Firmware", "Firmware"),
                    ("File", "File"),
                    ("Machine learning model", "Machine learning model"),
                    ("Data", "Data"),
                    ("Cryptographic asset", "Cryptographic asset"),
                ],
                max_length=24,
            ),
        ),
    ]
