# Generated by Django 6.0.7 on 2026-07-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_observation_general_rule_and_more"),
        ("licenses", "0021_license_component_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license_component",
            name="origin_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.service",
            ),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_components",
                to="core.product",
            ),
        ),
    ]
