# Generated by Django 6.1 on 2026-08-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_component"),
        ("licenses", "0022_alter_license_component_origin_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="component",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.component"),
        ),
    ]
