class Theme:
    THEME_LIGHT = "light"
    THEME_DARK = "dark"
    THEME_SYSTEM = "system"

    THEME_CHOICES = [
        (THEME_LIGHT, THEME_LIGHT),
        (THEME_DARK, THEME_DARK),
        (THEME_SYSTEM, THEME_SYSTEM),
    ]


class ListSize:
    LIST_SIZE_SMALL = "small"
    LIST_SIZE_MEDIUM = "medium"

    LIST_SIZE_CHOICES = [
        (LIST_SIZE_SMALL, LIST_SIZE_SMALL),
        (LIST_SIZE_MEDIUM, LIST_SIZE_MEDIUM),
    ]


class PackageInfo:
    PACKAGE_INFO_PREFERENCE_DEPS_DEV = "open/source/insights"
    PACKAGE_INFO_PREFERENCE_ECOSYSTE_MS = "ecosyste.ms"

    PACKAGE_INFO_PREFERENCE_CHOICES = [
        (PACKAGE_INFO_PREFERENCE_DEPS_DEV, PACKAGE_INFO_PREFERENCE_DEPS_DEV),
        (PACKAGE_INFO_PREFERENCE_ECOSYSTE_MS, PACKAGE_INFO_PREFERENCE_ECOSYSTE_MS),
    ]


class MetricsTimespan:
    METRICS_TIMESPAN_7_DAYS = "Week"
    METRICS_TIMESPAN_30_DAYS = "Month"
    METRICS_TIMESPAN_90_DAYS = "Quarter"
    METRICS_TIMESPAN_365_DAYS = "Year"

    METRICS_TIMESPAN_CHOICES = [
        (METRICS_TIMESPAN_7_DAYS, METRICS_TIMESPAN_7_DAYS),
        (METRICS_TIMESPAN_30_DAYS, METRICS_TIMESPAN_30_DAYS),
        (METRICS_TIMESPAN_90_DAYS, METRICS_TIMESPAN_90_DAYS),
        (METRICS_TIMESPAN_365_DAYS, METRICS_TIMESPAN_365_DAYS),
    ]
