class License_Policy_Evaluation_Result:
    RESULT_ALLOWED = "Allowed"
    RESULT_FORBIDDEN = "Forbidden"
    RESULT_IGNORED = "Ignored"
    RESULT_REVIEW_REQUIRED = "Review required"
    RESULT_UNKNOWN = "Unknown"

    RESULT_CHOICES = [
        (RESULT_ALLOWED, RESULT_ALLOWED),
        (RESULT_FORBIDDEN, RESULT_FORBIDDEN),
        (RESULT_IGNORED, RESULT_IGNORED),
        (RESULT_REVIEW_REQUIRED, RESULT_REVIEW_REQUIRED),
        (RESULT_UNKNOWN, RESULT_UNKNOWN),
    ]

    NUMERICAL_RESULTS = {
        RESULT_FORBIDDEN: 1,
        RESULT_REVIEW_REQUIRED: 2,
        RESULT_UNKNOWN: 3,
        RESULT_ALLOWED: 4,
        RESULT_IGNORED: 5,
    }


class Component_Type:
    TYPE_APPLICATION = "Application"
    TYPE_FRAMEWORK = "Framework"
    TYPE_LIBRARY = "Library"
    TYPE_CONTAINER = "Container"
    TYPE_PLATFORM = "Platform"
    TYPE_OPERATING_SYSTEM = "Operating system"
    TYPE_DEVICE = "Device"
    TYPE_DEVICE_DRIVER = "Device driver"
    TYPE_FIRMWARE = "Firmware"
    TYPE_FILE = "File"
    TYPE_MACHINE_LEARNING_MODEL = "Machine learning model"
    TYPE_DATA = "Data"
    TYPE_CRYPROGHRAPHIC_ASSET = "Cryptographic asset"

    TYPE_CHOICES = [
        (TYPE_APPLICATION, TYPE_APPLICATION),
        (TYPE_FRAMEWORK, TYPE_FRAMEWORK),
        (TYPE_LIBRARY, TYPE_LIBRARY),
        (TYPE_CONTAINER, TYPE_CONTAINER),
        (TYPE_PLATFORM, TYPE_PLATFORM),
        (TYPE_OPERATING_SYSTEM, TYPE_OPERATING_SYSTEM),
        (TYPE_DEVICE, TYPE_DEVICE),
        (TYPE_DEVICE_DRIVER, TYPE_DEVICE_DRIVER),
        (TYPE_FIRMWARE, TYPE_FIRMWARE),
        (TYPE_FILE, TYPE_FILE),
        (TYPE_MACHINE_LEARNING_MODEL, TYPE_MACHINE_LEARNING_MODEL),
        (TYPE_DATA, TYPE_DATA),
        (TYPE_CRYPROGHRAPHIC_ASSET, TYPE_CRYPROGHRAPHIC_ASSET),
    ]


NO_LICENSE_INFORMATION = "No license information"
