# Generated by Django 4.2.11 on 2024-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0010_rule_new_vex_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Not security", "Not security"),
                    ("Risk accepted", "Risk accepted"),
                    ("Affected", "Affected"),
                ],
                max_length=16,
            ),
        ),
    ]
