# Generated by Django 5.0.4 on 2024-05-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0011_alter_rule_new_status"),
        ("rules", "0011_rule_approval_date_rule_approval_remark_and_more"),
    ]

    operations = []
