# Generated by Django 5.0.6 on 2024-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0012_merge_20240506_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="new_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
