# Generated by Django 5.0.8 on 2024-09-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0013_rule_new_vex_remediations"),
        ("rules", "0013_rule_origin_kubernetes_qualified_resource"),
    ]

    operations = []
