# Generated by Django 5.1.2 on 2024-10-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_merge_20240903_1725'),
        ('rules', '0015_convert_unknown_data'),
    ]

    operations = [
    ]
