# Generated by Django 5.2.10 on 2026-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0016_alter_rule_new_vex_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="origin_component_purl",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
