# Generated by Django 5.1.3 on 2024-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_merge_20241028_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='approval_remark',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
