# Generated by Django 5.2.7 on 2025-10-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0016_alter_rule_new_vex_justification"),
        ("rules", "0017_alter_rule_approval_remark"),
    ]

    operations = []
