# Generated by Django 5.2.11 on 2026-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0017_rule_origin_component_purl"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="rego_module",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="type",
            field=models.CharField(choices=[("Fields", "Fields"), ("Rego", "Rego")], default="Fields", max_length=8),
        ),
    ]
