# Generated by Django 5.2.11 on 2026-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0018_rule_rego_module_rule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Affected", "Affected"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Not security", "Not security"),
                    ("Risk accepted", "Risk accepted"),
                ],
                max_length=16,
            ),
        ),
    ]
