# Generated by Django 5.2.10 on 2026-01-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0017_rule_origin_component_purl"),
        ("rules", "0018_merge_20251010_1715"),
    ]

    operations = []
