# Generated by Django 5.2.11 on 2026-02-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0019_alter_rule_new_status"),
        ("rules", "0019_merge_20260115_1242"),
    ]

    operations = []
