# Generated by Django 6.0.4 on 2026-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0020_merge_20260219_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='new_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Affected', 'Affected'), ('Resolved', 'Resolved'), ('Duplicate', 'Duplicate'), ('False positive', 'False positive'), ('In review', 'In review'), ('Not affected', 'Not affected'), ('Not security', 'Not security'), ('Risk accepted', 'Risk accepted')], max_length=16),
        ),
    ]
