# Generated by Django 5.2.12 on 2026-03-07 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_remove_observation_core_observ_origin__43587c_idx_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation_Title_Notified",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unknown", "Unknown"),
                            ("None", "None"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open", "Open"),
                            ("Affected", "Affected"),
                            ("Resolved", "Resolved"),
                            ("Duplicate", "Duplicate"),
                            ("False positive", "False positive"),
                            ("In review", "In review"),
                            ("Not affected", "Not affected"),
                            ("Not security", "Not security"),
                            ("Risk accepted", "Risk accepted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Exception", "Exception"),
                    ("Observation", "Observation"),
                    ("Observation title", "Observation title"),
                    ("Security gate", "Security gate"),
                    ("Task", "Task"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Observation_Notified",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unknown", "Unknown"),
                            ("None", "None"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open", "Open"),
                            ("Affected", "Affected"),
                            ("Resolved", "Resolved"),
                            ("Duplicate", "Duplicate"),
                            ("False positive", "False positive"),
                            ("In review", "In review"),
                            ("Not affected", "Not affected"),
                            ("Not security", "Not security"),
                            ("Risk accepted", "Risk accepted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "observation",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.observation"),
                ),
            ],
        ),
    ]
