# Generated by Django 6.1 on 2026-09-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_initialize_observation_components"),
        ("notifications", "0002_observation_title_notified_alter_notification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("security_gate_changed", models.BooleanField(default=False)),
                ("observation_new_changed", models.BooleanField(default=False)),
                ("observation_to_be_reviewed", models.BooleanField(default=False)),
                ("assessment_to_be_reviewed", models.BooleanField(default=False)),
                ("product_rule_to_be_reviewed", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("product", "user")},
            },
        ),
    ]
