# Generated by Django 6.1 on 2026-09-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_product_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_notification",
            name="assessment_approval_receipt",
            field=models.BooleanField(default=False),
        ),
    ]
