# Generated by Django 6.1.1 on 2026-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_product_notification_assessment_approval_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_notification",
            name="product_rule_approval_receipt",
            field=models.BooleanField(default=False),
        ),
    ]
