# Generated by Django 6.0.7 on 2026-07-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_observation_general_rule_and_more"),
        ("import_observations", "0016_api_configuration_migrate_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_configuration",
            name="automatic_import_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="api_configuration",
            name="automatic_import_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.service",
            ),
        ),
    ]
