# Generated by Django 6.1.1 on 2026-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_observations", "0017_alter_api_configuration_automatic_import_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VulnerableCode_Cache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purl", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField(default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
