# Generated by Django 5.0.4 on 2024-05-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0004_settings_background_exploits_import_crontab_hours_and_more"),
        ("commons", "0005_settings_feature_general_rules_need_approval"),
    ]

    operations = []
