# Generated by Django 5.0.6 on 2024-07-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0006_merge_20240506_1917"),
        ("commons", "0007_settings_risk_acceptance_expiry_crontab_hours_and_more"),
    ]

    operations = []
