# Generated by Django 5.1.1 on 2024-10-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_merge_20240710_1516'),
        ('commons', '0008_remove_settings_background_epss_import_crontab_hours_and_more'),
    ]

    operations = [
    ]
