# Generated by Django 5.1.2 on 2024-10-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0009_merge_20241004_1107"),
        ("commons", "0009_settings_password_validator_attribute_similarity_and_more"),
    ]

    operations = []
