# Generated by Django 5.1.2 on 2024-10-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0010_merge_20241015_1600"),
        ("commons", "0010_settings_feature_license_management_and_more"),
    ]

    operations = []
