# Generated by Django 5.1.2 on 2024-10-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0011_merge_20241022_1454"),
        ("commons", "0012_alter_settings_security_gate_threshold_unknown"),
    ]

    operations = []
