# Generated by Django 5.1.5 on 2025-03-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0013_merge_20241028_1602'),
        ('commons', '0015_settings_exploit_information_max_age_years_and_more'),
    ]

    operations = [
    ]
