# Generated by Django 5.2 on 2025-05-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0016_remove_notification_viewed_notification_and_more"),
        ("commons", "0017_remove_settings_background_exploits_import_crontab_hours_and_more"),
    ]

    operations = []
