# Generated by Django 5.2.4 on 2025-07-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0017_settings_periodic_task_max_entries"),
        ("commons", "0018_merge_20250512_1218"),
    ]

    operations = []
