# Generated by Django 5.2.9 on 2025-12-27 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0018_settings_vex_justification_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="oidc_clock_skew",
            field=models.IntegerField(
                default=0,
                help_text="Time margin in seconds for checks of issued at, not before and expiration of OIDC tokens",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
