# Generated by Django 5.2.7 on 2025-10-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0018_settings_vex_justification_style_and_more"),
        ("commons", "0019_merge_20250727_1457"),
    ]

    operations = []
