# Generated by Django 5.2.12 on 2026-03-11 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0019_settings_oidc_clock_skew"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_email_to",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_min_priority",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_min_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_ms_teams_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_parser_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SCA", "SCA"),
                    ("SAST", "SAST"),
                    ("DAST", "DAST"),
                    ("IAST", "IAST"),
                    ("Secrets", "Secrets"),
                    ("Infrastructure", "Infrastructure"),
                    ("Other", "Other"),
                    ("Manual", "Manual"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_slack_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="settings",
            name="observation_title_notification_statuses",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="settings",
            name="exception_ms_teams_webhook",
            field=models.TextField(
                blank=True, help_text="MS Teams webhook to send exception notifications", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="exception_slack_webhook",
            field=models.TextField(
                blank=True, help_text="Slack webhook to send exception notifications", max_length=2048
            ),
        ),
    ]
