# Generated by Django 5.2.9 on 2026-01-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0019_settings_oidc_clock_skew"),
        ("commons", "0020_merge_20251010_1716"),
    ]

    operations = []
