# Generated by Django 6.0.3 on 2026-03-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0020_settings_observation_title_notification_email_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="observation_count_from_metrics",
            field=models.BooleanField(default=False),
        ),
    ]
