# Generated by Django 6.0.4 on 2026-04-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0021_settings_observation_count_from_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_cross_scanner_deduplication",
            field=models.BooleanField(default=False),
        ),
    ]
