# Generated by Django 5.2.9 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0020_settings_observation_title_notification_email_to_and_more"),
        ("commons", "0021_merge_20260102_1149"),
    ]

    operations = []
