# Generated by Django 5.2.9 on 2026-03-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0021_settings_observation_count_from_metrics"),
        ("commons", "0022_merge_20260313"),
    ]

    operations = []
