# Generated by Django 6.0.8 on 2026-08-16 14:54

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0022_settings_feature_cross_scanner_deduplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_automatic_vulnerablecode_scanning",
            field=models.BooleanField(default=False, help_text="Enable automatic VulnerableCode scanning"),
        ),
        migrations.AddField(
            model_name="settings",
            name="vulnerablecode_base_url",
            field=models.CharField(blank=True, help_text="Base URL of the VulnerableCode instance", max_length=255),
        ),
        migrations.AddField(
            model_name="settings",
            name="vulnerablecode_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=255),
        ),
    ]
