# Generated by Django 6.1 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0023_settings_feature_automatic_vulnerablecode_scanning"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_show_product_header_chips",
            field=models.BooleanField(default=False),
        ),
    ]
