# Generated by Django 6.1.1 on 2026-09-18 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0025_settings_oidc_strict_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="vulnerablecode_cache_ttl_hours",
            field=models.IntegerField(
                default=23,
                help_text="Time to live for VulnerableCode cache in hours",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
