# Generated by Django 6.1.1 on 2026-09-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0026_settings_vulnerablecode_cache_ttl_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="oidc_api_token_max_authentication_age",
            field=models.IntegerField(
                default=5,
                help_text="Maximum age in minutes of the OIDC authentication to create or revoke a user API token, 0 disables the check",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
