# Generated by Django 5.2.10 on 2026-01-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0014_move_api_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setting_metrics_timespan",
            field=models.CharField(
                choices=[("Week", "Week"), ("Month", "Month"), ("Quarter", "Quarter"), ("Year", "Year")],
                default="Week",
                max_length=8,
            ),
        ),
    ]
