# Generated by Django 5.2.10 on 2026-01-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0015_user_setting_metrics_timespan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="setting_list_properties",
        ),
    ]
