# Generated by Django 5.2.10 on 2026-01-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0016_remove_user_setting_list_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="setting_theme",
            field=models.CharField(
                choices=[("light", "light"), ("dark", "dark"), ("system", "system")], default="light", max_length=6
            ),
        ),
    ]
