# Generated by Django 6.0.3 on 2026-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0017_add_system_theme_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setting_rows_per_page",
            field=models.IntegerField(
                choices=[(10, "Ten"), (25, "Twentyfive"), (50, "Fifty"), (100, "Hundred")], default=25
            ),
        ),
    ]
