# Generated by Django 6.1.1 on 2026-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0018_user_setting_rows_per_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_email_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_ms_teams_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_ms_teams_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_slack_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_slack_webhook",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
