#!/bin/sh

set -o errexit

rm -f /var/lib/sqlite/secobserve.db
python manage.py migrate

coverage run /app/manage.py test unittests
# coverage run /app/manage.py test unittests.notifications.services.test_send_notifications_observation_title
coverage report
coverage xml -o /home/coverage.xml
