export const EVALUATION_RESULT_FORBIDDEN = "Forbidden";
export const EVALUATION_RESULT_REVIEW_REQUIRED = "Review required";
export const EVALUATION_RESULT_UNKNOWN = "Unknown";
export const EVALUATION_RESULT_ALLOWED = "Allowed";
export const EVALUATION_RESULT_IGNORED = "Ignored";

export const EVALUATION_RESULT_CHOICES = [
    { id: EVALUATION_RESULT_FORBIDDEN, name: EVALUATION_RESULT_FORBIDDEN },
    { id: EVALUATION_RESULT_REVIEW_REQUIRED, name: EVALUATION_RESULT_REVIEW_REQUIRED },
    { id: EVALUATION_RESULT_UNKNOWN, name: EVALUATION_RESULT_UNKNOWN },
    { id: EVALUATION_RESULT_ALLOWED, name: EVALUATION_RESULT_ALLOWED },
    { id: EVALUATION_RESULT_IGNORED, name: EVALUATION_RESULT_IGNORED },
];

export const COMPONENT_TYPE_APPLICATION = "Application";
export const COMPONENT_TYPE_CONTAINER = "Container";
export const COMPONENT_TYPE_CRYPROGHRAPHIC_ASSET = "Cryptographic asset";
export const COMPONENT_TYPE_DATA = "Data";
export const COMPONENT_TYPE_DEVICE = "Device";
export const COMPONENT_TYPE_DEVICE_DRIVER = "Device driver";
export const COMPONENT_TYPE_FILE = "File";
export const COMPONENT_TYPE_FIRMWARE = "Firmware";
export const COMPONENT_TYPE_FRAMEWORK = "Framework";
export const COMPONENT_TYPE_LIBRARY = "Library";
export const COMPONENT_TYPE_MACHINE_LEARNING_MODEL = "Machine learning model";
export const COMPONENT_TYPE_OPERATING_SYSTEM = "Operating system";
export const COMPONENT_TYPE_PLATFORM = "Platform";

export const COMPONENT_TYPE_CHOICES = [
    { id: COMPONENT_TYPE_APPLICATION, name: COMPONENT_TYPE_APPLICATION },
    { id: COMPONENT_TYPE_CONTAINER, name: COMPONENT_TYPE_CONTAINER },
    { id: COMPONENT_TYPE_CRYPROGHRAPHIC_ASSET, name: COMPONENT_TYPE_CRYPROGHRAPHIC_ASSET },
    { id: COMPONENT_TYPE_DATA, name: COMPONENT_TYPE_DATA },
    { id: COMPONENT_TYPE_DEVICE, name: COMPONENT_TYPE_DEVICE },
    { id: COMPONENT_TYPE_DEVICE_DRIVER, name: COMPONENT_TYPE_DEVICE_DRIVER },
    { id: COMPONENT_TYPE_FILE, name: COMPONENT_TYPE_FILE },
    { id: COMPONENT_TYPE_FIRMWARE, name: COMPONENT_TYPE_FIRMWARE },
    { id: COMPONENT_TYPE_FRAMEWORK, name: COMPONENT_TYPE_FRAMEWORK },
    { id: COMPONENT_TYPE_LIBRARY, name: COMPONENT_TYPE_LIBRARY },
    { id: COMPONENT_TYPE_MACHINE_LEARNING_MODEL, name: COMPONENT_TYPE_MACHINE_LEARNING_MODEL },
    { id: COMPONENT_TYPE_OPERATING_SYSTEM, name: COMPONENT_TYPE_OPERATING_SYSTEM },
    { id: COMPONENT_TYPE_PLATFORM, name: COMPONENT_TYPE_PLATFORM },
];
